### Testar Rota Inicial
GET http://localhost:3000/

###

### Listar Filmes
GET http://localhost:3000/movies

###

### Criar Novo Filme
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "O Senhor dos Anéis: A Sociedade do Anel",
  "synopsis": "Um jovem hobbit recebe a tarefa de destruir um anel maligno para salvar a Terra-Média.",
  "genres": ["Fantasia", "Aventura", "Ação"],
  "duration": 178,
  "url_movie": "https://meustreaming.com/videos/lotr1.mp4",
  "url_poster": "https://meustreaming.com/imagens/lotr1.jpg",
  "directors": ["Peter Jackson"],
  "cast": ["Elijah Wood", "Ian McKellen", "Orlando Bloom"]
}

###

### Atualizar Filme (Substitua COLE_O_ID_AQUI pelo id gigante gerado no GET/POST)
PATCH http://localhost:3000/movies/576a8c1b-6610-465f-81c1-45a9f2405f6f
Content-Type: application/json

{
  "duration": 300
}

###

### Deletar Filme (Substitua COLE_O_ID_AQUI pelo id gigante gerado no GET/POST)
DELETE http://localhost:3000/movies/576a8c1b-6610-465f-81c1-45a9f2405f6f
